添加 jei_info.js 汉化
ShaBaiTianCN/Greed-the-Resource-3-Factory pull request #1
Opened 2022-05-09 04:13 UTC by luo-2233

关于血魔法束灵部分未汉化

2022-05-09 04:44 UTC, AnzhiZhang requested changes

2022-05-09 04:44 UTC, AnzhiZhang commented on kubejs/client_scripts/jei_info.js
>      e.add(Item.of('bloodmagic:upgradetome', {livingStats:{maxPoints:0,upgrades:[{exp:30000,key:"bloodmagic:fire_resist"}]}}),['Gift of Ignis','Grants fire resistance, higher levels last longer and re
等好心人把L74-L83翻译了

2022-05-10 10:16 UTC, AnzhiZhang commented
机器人用的有Bug的版本，更新不了了，不用管

2022-05-12 16:59 UTC, AnzhiZhang approved these changes
格式没问题

2022-05-12 17:07 UTC, AnzhiZhang commented
> 在 [这里](../actions/runs/2314748539) 下载此 PR 的最新打包。

建议游戏内测试一下正常加载再合并

测试正常

2022-05-13 11:19 UTC, Cactusstudent commented
这里的汉化结束了？

2022-05-13 11:50 UTC, AnzhiZhang commented
没问题可以合了

2022-05-13 12:17 UTC, Cactusstudent approved these changes
又看了一遍，没啥错误了，看谁有时间merge吧

2022-05-13 12:18 UTC, Cactusstudent approved these changes

2022-05-13 12:21 UTC, merged